#pragma once

#define IDI_APP 1

#define IDS_APP_NAME 100
#define IDS_PROP_LABEL 101
#define IDS_PROP_PINNED 102

#define IDS_MENU_PIN_FILE 110
#define IDS_MENU_PIN_FOLDER 111
#define IDS_MENU_UNPIN 112

#define IDS_TRAY_PINNED_ITEMS 120
#define IDS_TRAY_NONE 121
#define IDS_TRAY_REAPPLY 122
#define IDS_TRAY_CLEANUP 123
#define IDS_TRAY_STARTUP 124
#define IDS_TRAY_WEBSITE 125
#define IDS_TRAY_EXIT 126
#define IDS_TRAY_UNPIN_ITEM 127
#define IDS_TRAY_OPEN_ITEM 128
#define IDS_TRAY_DIALOGS 129

#define IDS_MSG_SETUP_PROMPT 130
#define IDS_MSG_SCHEMA_FAILED 131
#define IDS_MSG_CLEANUP_DONE 132
#define IDS_MSG_ALREADY_RUNNING 133
#define IDS_MSG_USAGE 134
#define IDS_MSG_UNINSTALLED 135
#define IDS_MSG_SETUP_DONE 136
